import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogDescription,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";

export function TermsModal({ trigger }: { trigger: React.ReactNode }) {
  return (
    <Dialog>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent className="max-w-2xl h-[80vh] bg-card border-white/10 flex flex-col p-0 gap-0">
        <DialogHeader className="p-6 pb-2">
          <DialogTitle className="font-display text-2xl text-primary">Terms of Service</DialogTitle>
          <DialogDescription>Last updated: January 2026</DialogDescription>
        </DialogHeader>
        <div className="flex-1 overflow-hidden p-6 pt-0">
          <ScrollArea className="h-full pr-4">
            <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
              <p>Welcome to Dunamis. By accessing our platform, you agree to these terms.</p>
              
              <h3 className="text-foreground font-bold text-lg">1. Access and Usage</h3>
              <p>Dunamis grants you a limited, non-exclusive license to access our prompt library for personal or professional use. You may not scrape, resell, or mass-distribute our content without explicit permission.</p>
              
              <h3 className="text-foreground font-bold text-lg">2. Intellectual Property</h3>
              <p>All prompts, designs, and code on this site are the intellectual property of Dunamis Inc. or its contributors. Your usage does not transfer ownership.</p>
              
              <h3 className="text-foreground font-bold text-lg">3. User Conduct</h3>
              <p>You agree not to misuse the platform, attempt to bypass security measures, or upload malicious content.</p>
              
              <h3 className="text-foreground font-bold text-lg">4. Disclaimer</h3>
              <p>Prompts are provided "as is". While we test for quality, AI outputs can vary. We are not responsible for the results generated by third-party AI models using our prompts.</p>
            </div>
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export function PrivacyModal({ trigger }: { trigger: React.ReactNode }) {
  return (
    <Dialog>
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent className="max-w-2xl h-[80vh] bg-card border-white/10 flex flex-col p-0 gap-0">
        <DialogHeader className="p-6 pb-2">
          <DialogTitle className="font-display text-2xl text-primary">Privacy Policy</DialogTitle>
          <DialogDescription>Your data is yours. We respect that.</DialogDescription>
        </DialogHeader>
        <div className="flex-1 overflow-hidden p-6 pt-0">
          <ScrollArea className="h-full pr-4">
            <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
              <h3 className="text-foreground font-bold text-lg">1. Data Collection</h3>
              <p>We collect minimal data necessary to provide our service: your email address (for authentication) and usage statistics (to improve our library).</p>
              
              <h3 className="text-foreground font-bold text-lg">2. No Third-Party Sales</h3>
              <p>We do not sell your personal data to advertisers or third parties. Ever.</p>
              
              <h3 className="text-foreground font-bold text-lg">3. Cookies</h3>
              <p>We use essential cookies to maintain your login session. We do not use invasive tracking pixels.</p>
              
              <h3 className="text-foreground font-bold text-lg">4. Security</h3>
              <p>Your data is encrypted in transit and at rest. We use industry-standard security practices to protect your information.</p>
            </div>
          </ScrollArea>
        </div>
      </DialogContent>
    </Dialog>
  );
}
